# Generated by Django 5.1 on 2024-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('email', models.EmailField(max_length=254)),
                ('student_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], default='Other', max_length=15)),
                ('education', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
