# Generated by Django 5.1 on 2024-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('1 курс', '1 курс'), ('2 курс', '2 курс'), ('3 курс', '3 курс'), ('4 курс', '4 курс')], default='1 курс', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='sciences', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=15),
        ),
    ]
