# Generated by Django 5.1 on 2024-09-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_subject_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
    ]
