# Generated by Django 5.1 on 2024-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_grade_grade_alter_grade_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=3),
        ),
    ]
